### ISSUE TITLE
Help with installation?

### ISSUE THREAD

**Issue by rmosolgo** [Shopify/graphql-parser#3]
Hi, thanks for this great project! I'm excited to try using in in [graphql-ruby](https://github.com/rmosolgo/graphql-ruby). 

But, I'm sorry to say that I know _nothing_ about Ruby C extensions. Actually, I know nothing about C at all -- I'm just a simple Ruby guy :( I tried adding the gem to `graphql-ruby` and this is how far I got:

- Add a runtime dependency to the gemspec 
- Bundle install
- Fail to install: 

```
# ... 
Installing graphql-parser 0.0.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/rmosolgo/.rbenv/versions/2.1.0/bin/ruby extconf.rb
checking for main() in -lgraphqlparser... no
missing libgraphqlparser
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/rmosolgo/.rbenv/versions/2.1.0/bin/ruby
	--with-graphql-dir
	--without-graphql-dir
	--with-graphql-include
	--without-graphql-include=${graphql-dir}/include
	--with-graphql-lib
	--without-graphql-lib=${graphql-dir}/lib
	--with-graphqlparserlib
	--without-graphqlparserlib

extconf failed, exit code 1

Gem files will remain installed in /Users/rmosolgo/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/graphql-parser-0.0.2 for inspection.
Results logged to /Users/rmosolgo/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/graphql-parser-0.0.2/gem_make.out
An error occurred while installing graphql-parser (0.0.2), and Bundler cannot continue.
Make sure that `gem install graphql-parser -v '0.0.2'` succeeds before bundling.
```

Normally, that would be fixed by installing a dependency with Homebrew. Is there an equivalent in this case? 

Thanks!

**Comment by hwhelchel** [comment]
I'm interested in helping out getting this integrated into @rmosolgo's library but haven't been able to get this to `bundle` too. I've tried moving various parts of `libgraphqlparser` to `/usr/local/lib` because it looks like the `extconf.rb` looks there for the library. 

https://github.com/Shopify/graphql-parser/blob/master/ext/graphql_parser/extconf.rb

I'm interested in making a homebrew formula for `libgraphqlparser` to make it easier for future developers to install. Also interested in working on integrating this into `graphql-ruby` if you would like help.

Thanks!

**Comment by dylanahsmith** [comment]
This does require installing libgraphqlparser to compile the extension.  It isn't available through homebrew, but having that added would be great.

libgraphqlparser uses CMake to generate the makefile, then you can just use make to build and install it.

1. `cmake .`
2. `make`
3. `make install`

CMake will complain if you are missing a dependancy (e.g. Flex or Bison) or the installed version isn't compatible with libgraphqlparser.

It sounds like the documentation could be improved upstream, since this does seem to be confusion about installed it rather than how to install this gem once it is installed.

**Comment by swolchok** [comment]
> CMake will complain if you are missing a dependancy (e.g. Flex or Bison) or the installed version isn't compatible with libgraphqlparser.

The check for Flex and Bison is intended to be a "soft" check -- if the check fails, it should build anyway using the checked-in output from those tools. Please file a github issue if that's not working!

**Comment by rmosolgo** [comment]
Oops, I got this going a while back by installing with Homebrew: 

```
brew install libgraphqlparser
```
